source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'rainyShinyCloudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic 

    pod 'Alamofire', '~> 4.4'

end
